# generated by systemoneprompts — do not edit. source: score.toml sha256:bb7c2690e07c3350e5b6ffc8ebf534a64361765bda2f7e3dfebf13a94b2b6921
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Frustration score',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _ticket_RequiredState(TypedDict):
    message: str
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'frustration': {
        'type': 'score',
        'instructions': {
            'question': 'How frustrated does the customer appear?',
            'inspect': '`ticket.message`',
        },
        'criteria': [
            {
                'what': 'Calm and matter-of-fact',
                'signals': [
                    'Neutral wording',
                ],
            },
            {
                'what': 'Frustrated but civil',
                'signals': [
                    'Expresses annoyance',
                ],
            },
            {
                'what': 'Very angry or threatening to leave',
                'signals': [
                    'Hostile language',
                ],
            },
        ],
    },
}
class _frustration_Answer(TypedDict):
    type: Literal["score"]
    score: float
    confidence: float
    legend: dict[str, Any]
    probabilities: dict[str, float]
class Answers(TypedDict):
    frustration: _frustration_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'customer.high_frustration': {
        'ref': 'frustration',
        'score': {
            'gte': 1.5,
        },
    },
}
Factors = TypedDict('Factors', {'customer.high_frustration': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
