# generated by systemoneprompts — do not edit. source: batch.toml sha256:919916cdfceba72d2ced546ee29f35a903d0a6c7996f0fd96037824018312891
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Map-reduce ticket batch',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _ticket_RequiredState(TypedDict):
    message: str
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'topic': {
        'type': 'choice',
        'instructions': 'Which team should handle `ticket.message`?',
        'criteria': {
            'billing': 'Charges, invoices, refunds',
            'orders': 'Shipments and deliveries',
            'account': 'Login and profile',
        },
    },
    'urgent': {
        'type': 'noul',
        'instructions': 'Does `ticket.message` convey urgency?',
    },
}
class _topic_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['billing', 'orders', 'account']
    confidence: float
    probabilities: dict[str, float]
class _urgent_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class Answers(TypedDict):
    topic: _topic_Answer
    urgent: _urgent_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'topic.billing': {
        'ref': 'topic',
        'choice': 'billing',
    },
    'urgent.yes': {
        'ref': 'urgent',
        'noul': {
            'gte': 0.5,
        },
    },
}
Factors = TypedDict('Factors', {'topic.billing': bool, 'urgent.yes': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
