# generated by systemoneprompts — do not edit. source: nested-state.toml sha256:d716bc108ea6741407f3d426c2a3de8db16d6bdcab540c39c1a7582b85b54b30
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Nested state paths',
    'version': '0.1.0',
    'description': 'Index paths in [requires] and backtick lint',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'support.tickets[0].message': 'string',
    'support.tickets[0].id': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _tickets__support_RequiredStateItem(TypedDict):
    message: str
    id: str
class _support_RequiredState(TypedDict):
    tickets: list[_tickets__support_RequiredStateItem]
class RequiredState(TypedDict):
    support: _support_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'urgent': {
        'type': 'noul',
        'instructions': {
            'question': 'Does `support.tickets[0].message` convey urgency?',
            'inspect': '`support.tickets[0].message`',
        },
        'criteria': {
            'true': 'The first ticket asks for immediate help',
            'false': 'The first ticket is routine',
        },
    },
}
class _urgent_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class Answers(TypedDict):
    urgent: _urgent_Answer
factor_definitions: dict[str, dict[str, Any]] = {}
Factors = dict[str, bool]
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
