# generated by systemoneprompts — do not edit. source: routing.toml sha256:cf286c848fd5e99b8902bcbaa22bf9ecf093cb1b3ed8e842e0edcafbc1477bbe
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Confidence routing',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _ticket_RequiredState(TypedDict):
    message: str
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'topic': {
        'type': 'choice',
        'instructions': 'Which team should handle `ticket.message`?',
        'criteria': {
            'billing': 'Charges, invoices, refunds',
            'orders': 'Shipments and deliveries',
            'account': 'Login and profile',
        },
    },
    'refund_requested': {
        'type': 'noul',
        'instructions': 'Does `ticket.message` explicitly request a refund?',
    },
}
class _topic_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['billing', 'orders', 'account']
    confidence: float
    probabilities: dict[str, float]
class _refund_requested_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class Answers(TypedDict):
    topic: _topic_Answer
    refund_requested: _refund_requested_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'topic.confident': {
        'ref': 'topic',
        'confidence': {
            'gte': 0.8,
        },
    },
    'refund.gray': {
        'ref': 'refund_requested',
        'noul': {
            'gt': 0.4,
            'lt': 0.6,
        },
    },
}
Factors = TypedDict('Factors', {'topic.confident': bool, 'refund.gray': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
