# generated by systemoneprompts — do not edit. source: choice.toml sha256:20b62721f0ed538d8e426f7227573b976e7b50bf7a66a842e12afbe64067db63
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Contrastive Choice',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _ticket_RequiredState(TypedDict):
    message: str
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'intent': {
        'type': 'choice',
        'instructions': {
            'question': 'What is the customer asking about in `ticket.message`?',
            'focus': 'Separate policy questions from status questions.',
        },
        'criteria': {
            'return_policy': {
                'what': 'Asks how returns work, what is allowed, or how to start a return',
                'not_for': 'A question about a specific shipment already in progress',
                'examples': [
                    'What is your return window?',
                    'Can I return a used item?',
                ],
            },
            'return_status': {
                'what': 'Asks where a specific return or replacement stands',
                'not_for': 'A general question about the return policy',
                'examples': [
                    'Where is my refund for R-22?',
                    'Has my return been received?',
                ],
            },
        },
    },
}
class _intent_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['return_policy', 'return_status']
    confidence: float
    probabilities: dict[str, float]
class Answers(TypedDict):
    intent: _intent_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'intent.policy': {
        'ref': 'intent',
        'choice': 'return_policy',
    },
    'intent.status': {
        'ref': 'intent',
        'choice': 'return_status',
    },
}
Factors = TypedDict('Factors', {'intent.policy': bool, 'intent.status': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
