// generated by systemoneprompts — do not edit. source: fields.toml sha256:d5421d8a74c6e493becd77713e79488db092116f96aac3437059bdc9bbd67d91
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Invoice field extraction",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "invoice.text": "string",
} as const;
export interface RequiredState {
  invoice: {
    text: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  total_present: {
    type: "noul",
    instructions: {
      field: {
        name: "total",
        type: "currency",
      },
      question: "Is a payable total stated in `invoice.text`?",
      focus: "Look for a final amount due, not a line-item price.",
    },
  },
  currency: {
    type: "choice",
    instructions: {
      field: {
        name: "currency",
        type: "code",
      },
      question: "Which currency is the invoice total in?",
    },
    criteria: {
      USD: "US dollars",
      EUR: "Euros",
      GBP: "Pounds sterling",
      other: "Another currency or unspecified",
    },
  },
  amount_magnitude: {
    type: "score",
    instructions: {
      field: {
        name: "total",
        type: "currency",
      },
      question: "How large is the stated total in `invoice.text`?",
    },
    criteria: [
      "Under 100",
      "100 to 1000",
      "Over 1000",
    ],
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "total.verified": {
    ref: "total_present",
    noul: {
      gte: 0.7,
    },
  },
  "currency.usd": {
    ref: "currency",
    choice: "USD",
  },
  "amount.large": {
    ref: "amount_magnitude",
    score: {
      gte: 1.5,
    },
  },
} as const;
export interface Factors {
  "total.verified": boolean;
  "currency.usd": boolean;
  "amount.large": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
