# generated by systemoneprompts — do not edit. source: taxonomy.toml sha256:a5e3f023ccdf94a8bbcc2401cf4e768cb84cd757c8b806d3990310ea0c839489
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Taxonomy walk helper',
    'version': '0.1.0',
    'description': 'The walk is in run.ts; this file documents the leaf questions.',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'listing.title': 'string',
    'listing.description': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _listing_RequiredState(TypedDict):
    title: str
    description: str
class RequiredState(TypedDict):
    listing: _listing_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'department': {
        'type': 'choice',
        'instructions': {
            'question': 'Which top-level department fits `listing.title`?',
            'focus': "Use the listing's intended use, not just the word bottle.",
        },
        'criteria': {
            'Sporting Goods': 'Athletic and outdoor equipment, including cycling accessories',
            'Home & Kitchen': 'Household drinkware and kitchen goods',
        },
    },
}
class _department_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['Sporting Goods', 'Home & Kitchen']
    confidence: float
    probabilities: dict[str, float]
class Answers(TypedDict):
    department: _department_Answer
factor_definitions: dict[str, dict[str, Any]] = {}
Factors = dict[str, bool]
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
