import { describe, expect, test } from "bun:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type EntryType, generate, SystemOnePromptsError } from "../src/index.ts";
import { fixture, root, tsc } from "./helpers.ts";

describe("generate", () => {
  test("is deterministic", () => {
    const source = fixture("golden/triage.toml");
    const a = generate(source, { filename: "triage.toml" });
    const b = generate(source, { filename: "triage.toml" });
    expect(a).toBe(b);
  });

  test("embeds source hash and exports the public surface", () => {
    const out = generate(fixture("golden/triage.toml"), { filename: "triage.toml" });
    expect(out).toContain(
      "generated by systemoneprompts — do not edit. source: triage.toml sha256:",
    );
    expect(out).toContain("export const meta");
    expect(out).toContain("export const data");
    expect(out).toContain("export const data");
    expect(out).toContain('export const model = "jev-latest";');
    expect(out).toContain("export const requires");
    expect(out).toContain("export interface RequiredState {");
    expect(out).not.toContain("};\nexport const assertState");
    expect(out).toContain("export const assertState");
    expect(out).toContain("export const questions");
    expect(out).toContain("as const satisfies Questions");
    expect(out).toContain("export type Answers");
    expect(out).toContain("export const factorDefinitions");
    expect(out).toContain("export interface Factors");
    expect(out).toContain("export const evaluateFactors");
    expect(out).toContain('"spam.requests_credentials"');
    expect(out).toContain("ticket: {");
    expect(out).toContain("message: string;");
    expect(out).toContain("[k: string]: JsonValue;");
  });

  test("lists every error when the definition does not check", () => {
    const bad = `
[questions.topic]
type = "choice"
instructions = "Which?"
criteria = { billing = "Charges", orders = "Shipments" }

[questions.frustration]
type = "score"
instructions = "How?"
criteria = ["Calm", "Angry"]

[factors]
x = { ref = "topic", choice = "nope" }
y = { all = ["frustration"] }
`;
    let caught: unknown;
    try {
      generate(bad, { filename: "bad.toml" });
    } catch (error) {
      caught = error;
    }
    expect(caught).toBeInstanceOf(SystemOnePromptsError);
    const err = caught as SystemOnePromptsError;
    expect(err.diagnostics.map((d) => d.code).sort()).toEqual([
      "non-boolean-ref",
      "unknown-option",
    ]);
    expect(err.message).toContain("bad.toml:");
  });

  test("generated output typechecks and the narrowed state is a valid EntryType", async () => {
    const dir = await mkdtemp(join(tmpdir(), "jev-generated-"));
    const files = {
      "triage.generated.ts": generate(fixture("golden/triage.toml"), { filename: "triage.toml" }),
      "nomodel.generated.ts": generate(fixture("golden/noul-string.toml"), {
        filename: "noul-string.toml",
      }),
      "nofactors.generated.ts": generate(fixture("golden/score-strings.toml"), {
        filename: "score-strings.toml",
      }),
      "reserved.generated.ts": generate(`
"__proto__" = "metadata"
[requires]
"__proto__.value" = "string"
[questions.constructor]
type = "choice"
criteria = { "__proto__" = "prototype label", ordinary = "ordinary label" }
[factors]
"__proto__" = { ref = "constructor", choice = "__proto__" }
`),
      "reserved-question.generated.ts": generate('[questions."__proto__"]\ntype = "noul"'),
      "data.generated.ts": generate(`
[data]
"__proto__" = { value = "safe" }
topics = [{ label = "Delivery prices" }]

[questions.ok]
type = "noul"
`),
      "app.ts": `
import type { EntryType, TypeSafeClient } from "systemoneprompts";
import { assertState, evaluateFactors, model, questions, type Factors } from "./triage.generated.ts";
import * as nomodel from "./nomodel.generated.ts";
import * as reserved from "./reserved.generated.ts";
import * as authored from "./data.generated.ts";

const authoredLabel: "Delivery prices" = authored.data.topics[0].label;
const authoredReserved: string = authored.data["__proto__"].value;
void authoredLabel; void authoredReserved;

export function specialKeys(state: unknown) {
  reserved.assertState(state);
  const value: string = state.__proto__.value;
  const factors = reserved.evaluateFactors({ constructor: {
    type: "choice", choice: "__proto__", confidence: 1,
    probabilities: { ["__proto__"]: 1, ordinary: 0 },
  } });
  const matches: boolean = factors.__proto__;
  return { value, matches };
}

export async function app(client: TypeSafeClient, state: unknown): Promise<Factors> {
  assertState(state);
  const response = await client.systemOne({ state, questions, model });
  const noul: number = response.answers["spam.requests_credentials"].noul;
  const label: "billing" | "orders" | "account" = response.answers.topic.choice;
  void noul; void label;
  return evaluateFactors(response.answers);
}

export async function noModel(client: TypeSafeClient, state: EntryType) {
  nomodel.assertState(state);
  return client.systemOne({ state, questions: nomodel.questions, model: nomodel.model });
}
`,
    };
    for (const [name, text] of Object.entries(files)) {
      await writeFile(join(dir, name), text);
    }
    await writeFile(
      join(dir, "tsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            strict: true,
            skipLibCheck: true,
            noEmit: true,
            allowImportingTsExtensions: true,
            types: ["node"],
            typeRoots: [join(root, "node_modules/@types")],
            baseUrl: ".",
            paths: {
              systemoneprompts: [join(root, "src/index.ts")],
            },
          },
          include: ["./*.ts"],
        },
        null,
        2,
      ),
    );
    const result = tsc(["-p", join(dir, "tsconfig.json")]);
    if (result.exitCode !== 0) throw new Error(result.output);
    expect(result.exitCode).toBe(0);
    const reserved = await import(join(dir, "reserved.generated.ts"));
    expect(Object.hasOwn(reserved.meta, "__proto__")).toBe(true);
    expect(Object.getOwnPropertyDescriptor(reserved.meta, "__proto__")?.value).toBe("metadata");
    expect(Object.keys(reserved.questions.constructor.criteria)).toEqual(["__proto__", "ordinary"]);
    const factors = reserved.evaluateFactors({
      constructor: {
        type: "choice",
        choice: "__proto__",
        confidence: 1,
        probabilities: { ["__proto__"]: 1, ordinary: 0 },
      },
    });
    expect(Object.hasOwn(factors, "__proto__")).toBe(true);
    expect(Object.getOwnPropertyDescriptor(factors, "__proto__")?.value).toBe(true);
    const reservedQuestion = await import(join(dir, "reserved-question.generated.ts"));
    expect(Object.keys(reservedQuestion.questions)).toEqual(["__proto__"]);
    const authored = await import(join(dir, "data.generated.ts"));
    expect(authored.data.topics[0]?.label).toBe("Delivery prices");
    expect(Object.hasOwn(authored.data, "__proto__")).toBe(true);
    expect(Object.getOwnPropertyDescriptor(authored.data, "__proto__")?.value).toEqual({
      value: "safe",
    });
  });

  test("empty requirements preserve every EntryType state", async () => {
    const output = generate('[questions.ok]\ntype = "noul"');
    expect(output).toContain("export type RequiredState = EntryType;");
    expect(output).toContain(
      "export const assertState: (state: RequiredState) => void = createStateAssert(requires);",
    );
    expect(output).not.toContain("StateAssert<RequiredState>");

    const dir = await mkdtemp(join(tmpdir(), "jev-empty-state-"));
    await writeFile(join(dir, "empty.generated.ts"), output);
    await writeFile(
      join(dir, "app.ts"),
      `import type { EntryType } from "systemoneprompts";
import { assertState, type RequiredState } from "./empty.generated.ts";

export function checked(state: EntryType): RequiredState {
  assertState(state);
  return state;
}
`,
    );
    await writeFile(
      join(dir, "tsconfig.json"),
      JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "NodeNext",
            moduleResolution: "NodeNext",
            strict: true,
            skipLibCheck: true,
            noEmit: true,
            allowImportingTsExtensions: true,
            types: ["node"],
            typeRoots: [join(root, "node_modules/@types")],
            baseUrl: ".",
            paths: {
              systemoneprompts: [join(root, "src/index.ts")],
            },
          },
          include: ["./*.ts"],
        },
        null,
        2,
      ),
    );
    const result = tsc(["-p", join(dir, "tsconfig.json")]);
    if (result.exitCode !== 0) throw new Error(result.output);

    const generated = await import(join(dir, "empty.generated.ts"));
    for (const state of ["text", null, [], { nested: true }] satisfies EntryType[]) {
      generated.assertState(state);
    }
  });
});
