# generated by systemoneprompts — do not edit. source: verify.toml sha256:7d48432ae49caf835a3b530c975d9e875d7e0c436d90e4d73476bd4331965f1b
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Tool-call verification',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'trace.tool': 'string',
    'trace.arguments': 'object',
    'trace.result': 'object',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _trace_RequiredState(TypedDict):
    tool: str
    arguments: dict[str, Any]
    result: dict[str, Any]
class RequiredState(TypedDict):
    trace: _trace_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'tool_exists': {
        'type': 'noul',
        'instructions': 'Does `trace.tool` name a real function that was invoked?',
    },
    'args_match_schema': {
        'type': 'noul',
        'instructions': {
            'question': "Do `trace.arguments` match the tool's expected fields?",
            'inspect': '`trace.arguments`',
        },
    },
    'result_addresses_args': {
        'type': 'noul',
        'instructions': {
            'question': 'Does `trace.result` answer the request implied by `trace.arguments`?',
            'compare': [
                '`trace.arguments`',
                '`trace.result`',
            ],
        },
    },
}
class _tool_exists_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _args_match_schema_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _result_addresses_args_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class Answers(TypedDict):
    tool_exists: _tool_exists_Answer
    args_match_schema: _args_match_schema_Answer
    result_addresses_args: _result_addresses_args_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'verified': {
        'all': [
            'tool_exists',
            'args_match_schema',
            'result_addresses_args',
        ],
    },
}
class Factors(TypedDict):
    verified: bool
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
