// generated by systemoneprompts — do not edit. source: spam.toml sha256:a6b8fc53ae1fccae6e092b46c186442c464e7511ae66c169dbe81a306f415dda
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Spam decomposition",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
  "ticket.sender.email": "string",
  "ticket.sender.display_name": "string",
  "policy.sensitive_credentials": "array",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    sender: {
      email: string;
      display_name: string;
      [k: string]: JsonValue;
    };
    [k: string]: JsonValue;
  };
  policy: {
    sensitive_credentials: JsonValue[];
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  broad_spam: {
    type: "noul",
    instructions: "Is `ticket.message` spam?",
  },
  requests_credentials: {
    type: "noul",
    instructions: {
      question: "Does the message request a sensitive credential?",
      compare: [
        "`ticket.message`",
        "`policy.sensitive_credentials`",
      ],
    },
    criteria: {
      true: {
        what: "Asks the recipient to disclose a listed credential",
        examples: [
          "Reply with your password",
        ],
      },
      false: {
        what: "Does not ask the recipient to disclose a credential",
      },
    },
  },
  sender_identity_mismatch: {
    type: "noul",
    instructions: {
      question: "Does the claimed sender identity conflict with its domain?",
      compare: [
        "`ticket.sender.display_name`",
        "`ticket.sender.email`",
      ],
    },
  },
  unexpected_reward: {
    type: "noul",
    instructions: {
      question: "Does the message announce an unexpected reward?",
      inspect: "`ticket.message`",
    },
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "spam.corroborated": {
    at_least: 2,
    of: [
      "requests_credentials",
      "sender_identity_mismatch",
      "unexpected_reward",
    ],
  },
} as const;
export interface Factors {
  "spam.corroborated": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
