# generated by systemoneprompts — do not edit. source: fields.toml sha256:d5421d8a74c6e493becd77713e79488db092116f96aac3437059bdc9bbd67d91
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Invoice field extraction',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'invoice.text': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _invoice_RequiredState(TypedDict):
    text: str
class RequiredState(TypedDict):
    invoice: _invoice_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'total_present': {
        'type': 'noul',
        'instructions': {
            'field': {
                'name': 'total',
                'type': 'currency',
            },
            'question': 'Is a payable total stated in `invoice.text`?',
            'focus': 'Look for a final amount due, not a line-item price.',
        },
    },
    'currency': {
        'type': 'choice',
        'instructions': {
            'field': {
                'name': 'currency',
                'type': 'code',
            },
            'question': 'Which currency is the invoice total in?',
        },
        'criteria': {
            'USD': 'US dollars',
            'EUR': 'Euros',
            'GBP': 'Pounds sterling',
            'other': 'Another currency or unspecified',
        },
    },
    'amount_magnitude': {
        'type': 'score',
        'instructions': {
            'field': {
                'name': 'total',
                'type': 'currency',
            },
            'question': 'How large is the stated total in `invoice.text`?',
        },
        'criteria': [
            'Under 100',
            '100 to 1000',
            'Over 1000',
        ],
    },
}
class _total_present_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _currency_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['USD', 'EUR', 'GBP', 'other']
    confidence: float
    probabilities: dict[str, float]
class _amount_magnitude_Answer(TypedDict):
    type: Literal["score"]
    score: float
    confidence: float
    legend: dict[str, Any]
    probabilities: dict[str, float]
class Answers(TypedDict):
    total_present: _total_present_Answer
    currency: _currency_Answer
    amount_magnitude: _amount_magnitude_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'total.verified': {
        'ref': 'total_present',
        'noul': {
            'gte': 0.7,
        },
    },
    'currency.usd': {
        'ref': 'currency',
        'choice': 'USD',
    },
    'amount.large': {
        'ref': 'amount_magnitude',
        'score': {
            'gte': 1.5,
        },
    },
}
Factors = TypedDict('Factors', {'total.verified': bool, 'currency.usd': bool, 'amount.large': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
