// generated by systemoneprompts — do not edit. source: choice.toml sha256:20b62721f0ed538d8e426f7227573b976e7b50bf7a66a842e12afbe64067db63
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Contrastive Choice",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  intent: {
    type: "choice",
    instructions: {
      question: "What is the customer asking about in `ticket.message`?",
      focus: "Separate policy questions from status questions.",
    },
    criteria: {
      return_policy: {
        what: "Asks how returns work, what is allowed, or how to start a return",
        not_for: "A question about a specific shipment already in progress",
        examples: [
          "What is your return window?",
          "Can I return a used item?",
        ],
      },
      return_status: {
        what: "Asks where a specific return or replacement stands",
        not_for: "A general question about the return policy",
        examples: [
          "Where is my refund for R-22?",
          "Has my return been received?",
        ],
      },
    },
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "intent.policy": {
    ref: "intent",
    choice: "return_policy",
  },
  "intent.status": {
    ref: "intent",
    choice: "return_status",
  },
} as const;
export interface Factors {
  "intent.policy": boolean;
  "intent.status": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
