// generated by systemoneprompts — do not edit. source: nested-state.toml sha256:d716bc108ea6741407f3d426c2a3de8db16d6bdcab540c39c1a7582b85b54b30
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Nested state paths",
  version: "0.1.0",
  description: "Index paths in [requires] and backtick lint",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "support.tickets[0].message": "string",
  "support.tickets[0].id": "string",
} as const;
export interface RequiredState {
  support: {
    tickets: {
      message: string;
      id: string;
      [k: string]: JsonValue;
    }[];
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  urgent: {
    type: "noul",
    instructions: {
      question: "Does `support.tickets[0].message` convey urgency?",
      inspect: "`support.tickets[0].message`",
    },
    criteria: {
      true: "The first ticket asks for immediate help",
      false: "The first ticket is routine",
    },
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {} as const;
export type Factors = Record<never, boolean>;
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
