# generated by systemoneprompts — do not edit. source: triage.toml sha256:bef0ae4e8120c53b013780e370e1379ce87c0b723d3910e515e81543c055706b
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Support ticket triage',
    'version': '0.1.0',
    'description': 'Flagship workflow: seven questions from the TypeSafe how-to-build page',
    'owner': 'support-platform',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
    'ticket.sender.email': 'string',
    'ticket.sender.display_name': 'string',
    'customer.open_orders': 'array',
    'policy.sensitive_credentials': 'array',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _sender__ticket_RequiredState(TypedDict):
    email: str
    display_name: str
class _ticket_RequiredState(TypedDict):
    message: str
    sender: _sender__ticket_RequiredState
class _customer_RequiredState(TypedDict):
    open_orders: list[Any]
class _policy_RequiredState(TypedDict):
    sensitive_credentials: list[Any]
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
    customer: _customer_RequiredState
    policy: _policy_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'topic': {
        'type': 'choice',
        'instructions': {
            'question': 'Which team should handle `ticket.message`?',
            'focus': "Classify the customer's primary request.",
        },
        'criteria': {
            'billing': {
                'what': 'Charges, invoices, refunds, or subscriptions',
                'not_for': 'Order tracking or account access',
                'examples': [
                    'I was charged twice',
                    'Where is my refund?',
                ],
            },
            'orders': {
                'what': 'Order status, delivery, cancellation, or returns',
                'not_for': 'Charges or account access',
                'examples': [
                    'Where is my order?',
                    'Cancel my shipment',
                ],
            },
            'account': {
                'what': 'Login, profile, permissions, or security',
                'not_for': 'Charges or order tracking',
                'examples': [
                    'Reset my password',
                    'I cannot sign in',
                ],
            },
        },
    },
    'requests_credentials': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the message request a sensitive credential?',
            'compare': [
                '`ticket.message`',
                '`policy.sensitive_credentials`',
            ],
            'focus': 'Look for a request to disclose the credential itself.',
        },
        'criteria': {
            'true': {
                'what': 'Asks the recipient to disclose a listed credential',
                'examples': [
                    'Reply with your password',
                    'Send us your API key',
                ],
            },
            'false': {
                'what': 'Does not ask the recipient to disclose a credential',
                'not_for': 'A legitimate instruction to reset a credential',
                'examples': [
                    'Use this link to reset your password',
                ],
            },
        },
    },
    'sender_identity_mismatch': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the claimed sender identity conflict with its domain?',
            'compare': [
                '`ticket.sender.display_name`',
                '`ticket.sender.email`',
            ],
        },
    },
    'unexpected_reward': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the message announce an unexpected reward?',
            'inspect': '`ticket.message`',
        },
    },
    'refund_requested': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the customer explicitly request a refund or credit?',
            'inspect': '`ticket.message`',
        },
    },
    'mentions_open_order': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the message refer to a supplied open order?',
            'compare': [
                '`ticket.message`',
                '`customer.open_orders`',
            ],
        },
    },
    'frustration': {
        'type': 'score',
        'instructions': {
            'question': 'How frustrated does the customer appear?',
            'inspect': '`ticket.message`',
        },
        'criteria': [
            {
                'what': 'Calm and matter-of-fact',
                'signals': [
                    'Neutral wording',
                ],
            },
            {
                'what': 'Frustrated but civil',
            },
            {
                'what': 'Very angry or threatening to leave',
            },
        ],
    },
}
class _topic_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['billing', 'orders', 'account']
    confidence: float
    probabilities: dict[str, float]
class _requests_credentials_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _sender_identity_mismatch_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _unexpected_reward_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _refund_requested_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _mentions_open_order_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _frustration_Answer(TypedDict):
    type: Literal["score"]
    score: float
    confidence: float
    legend: dict[str, Any]
    probabilities: dict[str, float]
class Answers(TypedDict):
    topic: _topic_Answer
    requests_credentials: _requests_credentials_Answer
    sender_identity_mismatch: _sender_identity_mismatch_Answer
    unexpected_reward: _unexpected_reward_Answer
    refund_requested: _refund_requested_Answer
    mentions_open_order: _mentions_open_order_Answer
    frustration: _frustration_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'topic.billing': {
        'ref': 'topic',
        'choice': 'billing',
    },
    'topic.orders': {
        'ref': 'topic',
        'choice': 'orders',
    },
    'topic.confident': {
        'ref': 'topic',
        'confidence': {
            'gte': 0.75,
        },
    },
    'refund.strong_request': {
        'ref': 'refund_requested',
        'noul': {
            'gte': 0.7,
        },
    },
    'spam.corroborated': {
        'at_least': 2,
        'of': [
            'requests_credentials',
            'sender_identity_mismatch',
            'unexpected_reward',
        ],
    },
    'customer.high_frustration': {
        'ref': 'frustration',
        'score': {
            'gte': 1.5,
        },
        'confidence': {
            'gte': 0.7,
        },
    },
}
Factors = TypedDict('Factors', {'topic.billing': bool, 'topic.orders': bool, 'topic.confident': bool, 'refund.strong_request': bool, 'spam.corroborated': bool, 'customer.high_frustration': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
