// generated by systemoneprompts — do not edit. source: ticket.toml sha256:129672eb76f1afd87e3922e512324c3b954f3608a49d7f8a219b769ecdd5f671
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Cloudflare Clef ticket decisions",
  provider: "cloudflare",
} as const;
export const data = {} as const;
export const model = "clef";

export const requires = {
  "ticket.message": "string",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  duplicate: {
    type: "noul",
    instructions: "Does `ticket.message` report two charges for one order?",
    criteria: {
      true: "Two charges for one order",
      false: "Only one charge",
    },
  },
  department: {
    type: "choice",
    instructions: "Which department handles `ticket.message`?",
    criteria: {
      billing: "Payments and refunds",
      shipping: "Delivery and tracking",
    },
  },
  severity: {
    type: "score",
    instructions: "Rate the severity of `ticket.message`.",
    criteria: [
      "No issue",
      {
        issue: "Payment or delivery requires correction",
      },
      "Permanent account loss",
    ],
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  refund: {
    ref: "duplicate",
    noul: {
      gte: 0.8,
    },
  },
} as const;
export interface Factors {
  refund: boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
