# generated by systemoneprompts — do not edit. source: spam.toml sha256:a6b8fc53ae1fccae6e092b46c186442c464e7511ae66c169dbe81a306f415dda
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Spam decomposition',
    'version': '0.1.0',
}
data: dict[str, Any] = {}
model: str | None = 'jev-latest'
requires: dict[str, str] = {
    'ticket.message': 'string',
    'ticket.sender.email': 'string',
    'ticket.sender.display_name': 'string',
    'policy.sensitive_credentials': 'array',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _sender__ticket_RequiredState(TypedDict):
    email: str
    display_name: str
class _ticket_RequiredState(TypedDict):
    message: str
    sender: _sender__ticket_RequiredState
class _policy_RequiredState(TypedDict):
    sensitive_credentials: list[Any]
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
    policy: _policy_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'broad_spam': {
        'type': 'noul',
        'instructions': 'Is `ticket.message` spam?',
    },
    'requests_credentials': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the message request a sensitive credential?',
            'compare': [
                '`ticket.message`',
                '`policy.sensitive_credentials`',
            ],
        },
        'criteria': {
            'true': {
                'what': 'Asks the recipient to disclose a listed credential',
                'examples': [
                    'Reply with your password',
                ],
            },
            'false': {
                'what': 'Does not ask the recipient to disclose a credential',
            },
        },
    },
    'sender_identity_mismatch': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the claimed sender identity conflict with its domain?',
            'compare': [
                '`ticket.sender.display_name`',
                '`ticket.sender.email`',
            ],
        },
    },
    'unexpected_reward': {
        'type': 'noul',
        'instructions': {
            'question': 'Does the message announce an unexpected reward?',
            'inspect': '`ticket.message`',
        },
    },
}
class _broad_spam_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _requests_credentials_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _sender_identity_mismatch_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _unexpected_reward_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class Answers(TypedDict):
    broad_spam: _broad_spam_Answer
    requests_credentials: _requests_credentials_Answer
    sender_identity_mismatch: _sender_identity_mismatch_Answer
    unexpected_reward: _unexpected_reward_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'spam.corroborated': {
        'at_least': 2,
        'of': [
            'requests_credentials',
            'sender_identity_mismatch',
            'unexpected_reward',
        ],
    },
}
Factors = TypedDict('Factors', {'spam.corroborated': bool})
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
