// generated by systemoneprompts — do not edit. source: routing.toml sha256:cf286c848fd5e99b8902bcbaa22bf9ecf093cb1b3ed8e842e0edcafbc1477bbe
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Confidence routing",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  topic: {
    type: "choice",
    instructions: "Which team should handle `ticket.message`?",
    criteria: {
      billing: "Charges, invoices, refunds",
      orders: "Shipments and deliveries",
      account: "Login and profile",
    },
  },
  refund_requested: {
    type: "noul",
    instructions: "Does `ticket.message` explicitly request a refund?",
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "topic.confident": {
    ref: "topic",
    confidence: {
      gte: 0.8,
    },
  },
  "refund.gray": {
    ref: "refund_requested",
    noul: {
      gt: 0.4,
      lt: 0.6,
    },
  },
} as const;
export interface Factors {
  "topic.confident": boolean;
  "refund.gray": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
