"""Generate an importable Python module from a checked definition."""

from __future__ import annotations

import hashlib
import keyword
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .definition import Definition, check_definition
from .diagnostics import SystemOnePromptsError, errors_of
from .requirements import ALL_INDEX, PathSegment, RequirementType, parse_path

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _is_field_name(key: str) -> bool:
    """Usable as a class-syntax TypedDict field (keywords need the functional form)."""
    return bool(_IDENT.match(key)) and not keyword.iskeyword(key)


def generate(
    definition: Definition,
    output: str | Path,
    *,
    source_name: str | None = None,
) -> Path:
    errors = errors_of(check_definition(definition))
    if errors:
        raise SystemOnePromptsError(errors)
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    rendered = render_definition(definition, source_name=source_name)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", suffix=".tmp", dir=target.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(rendered)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, target)
    except BaseException:
        Path(temporary_name).unlink(missing_ok=True)
        raise
    return target


def render_definition(definition: Definition, *, source_name: str | None = None) -> str:
    """Render a checked definition without touching the filesystem."""
    name = _basename(source_name or definition.filename or "definition.toml")
    source_hash = hashlib.sha256((definition.source or "").encode("utf-8")).hexdigest()
    lines: list[str] = [
        f"# generated by systemoneprompts — do not edit. source: {name} sha256:{source_hash}",
        "from __future__ import annotations",
        "",
        "from collections.abc import Callable",
        "from typing import Any, Literal, TypedDict, cast",
        "",
        "from systemoneprompts import create_factor_evaluator, create_state_assert",
        "",
        f"meta: dict[str, Any] = {emit_value(definition.meta)}",
        f"data: dict[str, Any] = {emit_value(definition.data)}",
        (
            "model: str | None = None"
            if definition.model is None
            else f"model: str | None = {emit_value(definition.model)}"
        ),
        f"requires: dict[str, str] = {emit_value(dict(definition.requires))}",
        *_emit_required_state(definition.requires),
        "assert_state = create_state_assert(requires)",
        f"questions: dict[str, dict[str, Any]] = {emit_value(definition.questions)}",
        *_emit_answers_type(definition.questions),
        f"factor_definitions: dict[str, dict[str, Any]] = {emit_value(definition.factor_definitions)}",
        *_emit_factors_type(list(definition.factor_definitions)),
        "evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))",
        "",
    ]
    return "\n".join(lines)


def emit_value(value: Any, indent: int = 0) -> str:
    if value is None:
        return "None"
    if value is True:
        return "True"
    if value is False:
        return "False"
    if isinstance(value, str):
        return repr(value)
    if type(value) is int:
        return str(value)
    if type(value) is float:
        if value == 0:
            return "0.0" if str(value) == "0.0" else "0.0"
        return repr(value)
    if type(value) is list:
        if not value:
            return "[]"
        pad = "    " * (indent + 1)
        close = "    " * indent
        items = ",\n".join(f"{pad}{emit_value(item, indent + 1)}" for item in value)
        return f"[\n{items},\n{close}]"
    if isinstance(value, dict):
        entries = [(key, item) for key, item in value.items() if item is not None]
        if not entries:
            return "{}"
        pad = "    " * (indent + 1)
        close = "    " * indent
        items = ",\n".join(
            f"{pad}{emit_value(key)}: {emit_value(item, indent + 1)}"
            for key, item in entries
        )
        return f"{{\n{items},\n{close}}}"
    return repr(value)


class _TypeNode:
    __slots__ = ("kind", "python", "props", "element")

    def __init__(
        self,
        kind: str,
        python: str = "Any",
        props: dict[str, _TypeNode] | None = None,
        element: _TypeNode | None = None,
    ) -> None:
        self.kind = kind
        self.python = python
        self.props = props or {}
        self.element = element


def _emit_required_state(requires: dict[str, RequirementType]) -> list[str]:
    if not requires:
        return [
            "# Empty requirements stay unconstrained. assert_state returns None and does not narrow.",
            "RequiredState = dict[str, Any]",
        ]
    root = _TypeNode("object", props={})
    for path, expected in requires.items():
        segments = parse_path(path)
        if segments is None:
            continue
        _add_path(root, segments, _leaf_for(expected))
    aliases: list[str] = []
    rendered = _render_object(root.props, "RequiredState", aliases, set(), total_false=False)
    return [
        "# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.",
        "# assert_state returns None and does not provide TypeScript-style narrowing.",
        *aliases,
        rendered,
    ]


def _leaf_for(expected: RequirementType) -> _TypeNode:
    mapping = {
        "string": _TypeNode("leaf", "str"),
        "number": _TypeNode("leaf", "float | int"),
        "boolean": _TypeNode("leaf", "bool"),
        "null": _TypeNode("leaf", "None"),
        "exists": _TypeNode("leaf", "Any"),
        "array": _TypeNode("array", element=_TypeNode("leaf", "Any")),
        "object": _TypeNode("object", props={}),
    }
    return mapping[expected]


def _add_path(node: _TypeNode, segments: list[PathSegment], leaf: _TypeNode) -> None:
    head = segments[0]
    if isinstance(head, str):
        if node.kind != "object":
            return
        if len(segments) == 1:
            node.props[head] = _merge(node.props.get(head), leaf)
            return
        child = _ensure_container(node.props.get(head), segments[1])
        node.props[head] = child
        _add_path(child, segments[1:], leaf)
        return
    if node.kind != "array":
        return
    if len(segments) == 1:
        node.element = _merge(node.element, leaf)
        return
    child = _ensure_container(node.element, segments[1])
    node.element = child
    _add_path(child, segments[1:], leaf)


def _ensure_container(existing: _TypeNode | None, nxt: PathSegment) -> _TypeNode:
    if nxt is ALL_INDEX or isinstance(nxt, int):
        if existing and existing.kind == "array":
            return existing
        return _TypeNode("array", element=existing or _TypeNode("leaf", "Any"))
    if existing and existing.kind == "object":
        return existing
    return _TypeNode("object", props={})


def _merge(existing: _TypeNode | None, incoming: _TypeNode | None) -> _TypeNode:
    if existing is None:
        return incoming or _TypeNode("leaf", "Any")
    if incoming is None:
        return existing
    if existing.kind == "leaf" and existing.python == "Any":
        return incoming
    if incoming.kind == "leaf" and incoming.python == "Any":
        return existing
    if existing.kind == "object" and incoming.kind == "object":
        props = dict(existing.props)
        for key, node in incoming.props.items():
            props[key] = _merge(props.get(key), node)
        return _TypeNode("object", props=props)
    if existing.kind == "array" and incoming.kind == "array":
        return _TypeNode("array", element=_merge(existing.element, incoming.element))
    if existing.kind == "array" and incoming.kind == "object":
        return _TypeNode("array", element=_merge(existing.element, incoming))
    if existing.kind == "object" and incoming.kind == "array":
        return _TypeNode("array", element=_merge(existing, incoming.element))
    return incoming


def _render_node(node: _TypeNode, name: str, aliases: list[str], used: set[str]) -> str:
    if node.kind == "leaf":
        return node.python
    if node.kind == "array":
        element = node.element or _TypeNode("leaf", "Any")
        item_name = _unique(f"{name}Item", used) if _needs_alias(element) else name
        return f"list[{_render_node(element, item_name, aliases, used)}]"
    if not node.props:
        return "dict[str, Any]"
    aliases.append(_render_object(node.props, name, aliases, used, total_false=False))
    return name


def _needs_alias(node: _TypeNode) -> bool:
    """Whether rendering `node` emits a named TypedDict (directly or via a list element)."""
    if node.kind == "object":
        return bool(node.props)
    if node.kind == "array":
        return _needs_alias(node.element or _TypeNode("leaf", "Any"))
    return False


def _render_object(
    props: dict[str, _TypeNode],
    name: str,
    aliases: list[str],
    used: set[str],
    *,
    total_false: bool,
) -> str:
    if not props:
        return f"{name} = dict[str, Any]"
    annotations: list[tuple[str, str]] = []
    for key, node in props.items():
        nested_name = _safe_ident(key, name, used) if _needs_alias(node) else name
        annotations.append((key, _render_node(node, nested_name, aliases, used)))
    if any(not _is_field_name(key) for key, _ in annotations):
        body = ", ".join(f"{key!r}: {python}" for key, python in annotations)
        total = ", total=False" if total_false else ""
        return f"{name} = TypedDict({name!r}, {{{body}}}{total})"
    header = f"class {name}(TypedDict, total=False):" if total_false else f"class {name}(TypedDict):"
    fields = [f"    {key}: {python}" for key, python in annotations]
    return "\n".join([header, *fields])


def _emit_answers_type(questions: dict[str, dict[str, Any]]) -> list[str]:
    if not questions:
        return ["Answers = dict[str, Any]"]
    nested: list[str] = []
    fields: dict[str, str] = {}
    used: set[str] = set()
    for question_id, question in questions.items():
        alias = _safe_ident(question_id, "Answer", used)
        nested.extend(_emit_answer_alias(alias, question))
        fields[question_id] = alias
    if all(_is_field_name(question_id) for question_id in fields):
        body = [f"    {question_id}: {alias}" for question_id, alias in fields.items()]
        return [*nested, "class Answers(TypedDict):", *body]
    mapping = ", ".join(f"{key!r}: {alias}" for key, alias in fields.items())
    return [*nested, f"Answers = TypedDict('Answers', {{{mapping}}})"]


def _emit_answer_alias(name: str, question: dict[str, Any]) -> list[str]:
    question_type = question.get("type")
    if question_type == "choice" and isinstance(question.get("criteria"), dict):
        labels = [str(label) for label in question["criteria"]]
        literal = ", ".join(repr(label) for label in labels) if labels else "str"
        return [
            f"class {name}(TypedDict):",
            '    type: Literal["choice"]',
            f"    choice: Literal[{literal}]" if labels else "    choice: str",
            "    confidence: float",
            "    probabilities: dict[str, float]",
        ]
    if question_type == "score":
        return [
            f"class {name}(TypedDict):",
            '    type: Literal["score"]',
            "    score: float",
            "    confidence: float",
            "    legend: dict[str, Any]",
            "    probabilities: dict[str, float]",
        ]
    return [
        f"class {name}(TypedDict):",
        '    type: Literal["noul"]',
        "    noul: float",
    ]


def _emit_factors_type(ids: list[str]) -> list[str]:
    if not ids:
        return ["Factors = dict[str, bool]"]
    if any(not _is_field_name(factor_id) for factor_id in ids):
        body = ", ".join(f"{factor_id!r}: bool" for factor_id in ids)
        return [f"Factors = TypedDict('Factors', {{{body}}})"]
    fields = [f"    {factor_id}: bool" for factor_id in ids]
    return ["class Factors(TypedDict):", *fields]


def _safe_ident(value: str, suffix: str, used: set[str]) -> str:
    """Module-level alias name derived from an id; unique within `used`.

    Distinct ids can clean to the same text (`a.b`, `a_b`, `a-b`, or non-ASCII ids of
    equal length), so a numeric suffix keeps every alias distinct.
    """
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"Q_{cleaned}"
    return _unique(f"_{cleaned.strip('_') or 'id'}_{suffix}", used)


def _unique(base: str, used: set[str]) -> str:
    ident = base
    counter = 2
    while ident in used:
        ident = f"{base}{counter}"
        counter += 1
    used.add(ident)
    return ident


def _basename(path: str) -> str:
    return Path(path).name


__all__ = ["emit_value", "generate", "render_definition"]
