import { createHash } from "node:crypto";
import { checkDefinition } from "../definition/check.js";
import { errorsOf, SystemOnePromptsError } from "../definition/diagnostics.js";
import { parseDefinition } from "../definition/parse.js";
import type { Definition } from "../definition/schema.js";
import { emitRequiredState } from "./types.js";

export interface GenerateOptions {
  /** Used for diagnostics and, unless `sourceName` is given, for the header. */
  filename?: string;
  /** Name recorded in the generated header; defaults to the basename of `filename`. */
  sourceName?: string;
}

/**
 * Parse, check, and emit a `*.generated.ts` module. Throws `SystemOnePromptsError` listing every
 * error when the definition does not check. Output is deterministic: identical TOML
 * yields byte-identical TypeScript.
 */
export function generate(source: string, opts: GenerateOptions = {}): string {
  const filename = opts.filename;
  const def = parseDefinition(source, { filename });
  const errors = errorsOf(checkDefinition(def));
  if (errors.length > 0) throw new SystemOnePromptsError(errors);
  return emitGenerated(def, opts.sourceName ?? filename ?? "definition.toml");
}

/** Emit TypeScript for an already-checked definition. */
export function emitGenerated(def: Definition, sourceName: string): string {
  const hash = createHash("sha256").update(def.source.text).digest("hex");
  const lines: string[] = [];
  lines.push(
    `// generated by systemoneprompts — do not edit. source: ${basename(sourceName)} sha256:${hash}`,
  );
  lines.push(
    `import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";`,
  );
  lines.push(
    `import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";`,
  );
  lines.push("");
  lines.push(`export const meta = ${emitValue(metaObject(def))} as const;`);
  lines.push(`export const data = ${emitValue(def.data)} as const;`);
  lines.push(
    def.model === undefined
      ? "export const model: string | undefined = undefined;"
      : `export const model = ${JSON.stringify(def.model)};`,
  );
  lines.push("");
  lines.push(`export const requires = ${emitValue(def.requires)} as const;`);
  lines.push(emitRequiredState(def.requires));
  lines.push(
    Object.keys(def.requires).length === 0
      ? "export const assertState: (state: RequiredState) => void = createStateAssert(requires);"
      : "export const assertState: StateAssert<RequiredState> = createStateAssert(requires);",
  );
  lines.push("");
  lines.push(`export const questions = ${emitValue(def.questions)} as const satisfies Questions;`);
  lines.push("");
  lines.push(`export type Answers = SystemOneResult<typeof questions>["answers"];`);
  lines.push("");
  lines.push(`export const factorDefinitions = ${emitValue(def.factorDefinitions)} as const;`);
  lines.push(emitFactorsType(Object.keys(def.factorDefinitions)));
  lines.push(
    `export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);`,
  );
  lines.push("");
  return lines.join("\n");
}

function metaObject(def: Definition): Record<string, string | number | boolean> {
  const out: Record<string, string | number | boolean> = Object.create(null);
  for (const [key, value] of Object.entries(def.meta)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

function emitFactorsType(ids: string[]): string {
  if (ids.length === 0) {
    return "export type Factors = Record<never, boolean>;";
  }
  const body = ids.map((id) => `  ${quoteKey(id)}: boolean;`).join("\n");
  return `export interface Factors {\n${body}\n}`;
}

function emitValue(value: unknown, indent = 0): string {
  if (value === null) return "null";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const pad = "  ".repeat(indent + 1);
    const close = "  ".repeat(indent);
    const items = value.map((item) => `${pad}${emitValue(item, indent + 1)},`);
    return `[\n${items.join("\n")}\n${close}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    const pad = "  ".repeat(indent + 1);
    const close = "  ".repeat(indent);
    const items = entries.map(
      ([key, item]) => `${pad}${quoteKey(key)}: ${emitValue(item, indent + 1)},`,
    );
    return `{\n${items.join("\n")}\n${close}}`;
  }
  return "undefined";
}

function quoteKey(name: string): string {
  // Object-literal __proto__ syntax changes the prototype, even when quoted.
  if (name === "__proto__") return '["__proto__"]';
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function basename(path: string): string {
  const parts = path.split(/[/\\]/);
  return parts[parts.length - 1] ?? path;
}
