// generated by systemoneprompts — do not edit. source: triage.toml sha256:bef0ae4e8120c53b013780e370e1379ce87c0b723d3910e515e81543c055706b
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Support ticket triage",
  version: "0.1.0",
  description: "Flagship workflow: seven questions from the TypeSafe how-to-build page",
  owner: "support-platform",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
  "ticket.sender.email": "string",
  "ticket.sender.display_name": "string",
  "customer.open_orders": "array",
  "policy.sensitive_credentials": "array",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    sender: {
      email: string;
      display_name: string;
      [k: string]: JsonValue;
    };
    [k: string]: JsonValue;
  };
  customer: {
    open_orders: JsonValue[];
    [k: string]: JsonValue;
  };
  policy: {
    sensitive_credentials: JsonValue[];
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  topic: {
    type: "choice",
    instructions: {
      question: "Which team should handle `ticket.message`?",
      focus: "Classify the customer's primary request.",
    },
    criteria: {
      billing: {
        what: "Charges, invoices, refunds, or subscriptions",
        not_for: "Order tracking or account access",
        examples: [
          "I was charged twice",
          "Where is my refund?",
        ],
      },
      orders: {
        what: "Order status, delivery, cancellation, or returns",
        not_for: "Charges or account access",
        examples: [
          "Where is my order?",
          "Cancel my shipment",
        ],
      },
      account: {
        what: "Login, profile, permissions, or security",
        not_for: "Charges or order tracking",
        examples: [
          "Reset my password",
          "I cannot sign in",
        ],
      },
    },
  },
  requests_credentials: {
    type: "noul",
    instructions: {
      question: "Does the message request a sensitive credential?",
      compare: [
        "`ticket.message`",
        "`policy.sensitive_credentials`",
      ],
      focus: "Look for a request to disclose the credential itself.",
    },
    criteria: {
      true: {
        what: "Asks the recipient to disclose a listed credential",
        examples: [
          "Reply with your password",
          "Send us your API key",
        ],
      },
      false: {
        what: "Does not ask the recipient to disclose a credential",
        not_for: "A legitimate instruction to reset a credential",
        examples: [
          "Use this link to reset your password",
        ],
      },
    },
  },
  sender_identity_mismatch: {
    type: "noul",
    instructions: {
      question: "Does the claimed sender identity conflict with its domain?",
      compare: [
        "`ticket.sender.display_name`",
        "`ticket.sender.email`",
      ],
    },
  },
  unexpected_reward: {
    type: "noul",
    instructions: {
      question: "Does the message announce an unexpected reward?",
      inspect: "`ticket.message`",
    },
  },
  refund_requested: {
    type: "noul",
    instructions: {
      question: "Does the customer explicitly request a refund or credit?",
      inspect: "`ticket.message`",
    },
  },
  mentions_open_order: {
    type: "noul",
    instructions: {
      question: "Does the message refer to a supplied open order?",
      compare: [
        "`ticket.message`",
        "`customer.open_orders`",
      ],
    },
  },
  frustration: {
    type: "score",
    instructions: {
      question: "How frustrated does the customer appear?",
      inspect: "`ticket.message`",
    },
    criteria: [
      {
        what: "Calm and matter-of-fact",
        signals: [
          "Neutral wording",
        ],
      },
      {
        what: "Frustrated but civil",
      },
      {
        what: "Very angry or threatening to leave",
      },
    ],
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "topic.billing": {
    ref: "topic",
    choice: "billing",
  },
  "topic.orders": {
    ref: "topic",
    choice: "orders",
  },
  "topic.confident": {
    ref: "topic",
    confidence: {
      gte: 0.75,
    },
  },
  "refund.strong_request": {
    ref: "refund_requested",
    noul: {
      gte: 0.7,
    },
  },
  "spam.corroborated": {
    at_least: 2,
    of: [
      "requests_credentials",
      "sender_identity_mismatch",
      "unexpected_reward",
    ],
  },
  "customer.high_frustration": {
    ref: "frustration",
    score: {
      gte: 1.5,
    },
    confidence: {
      gte: 0.7,
    },
  },
} as const;
export interface Factors {
  "topic.billing": boolean;
  "topic.orders": boolean;
  "topic.confident": boolean;
  "refund.strong_request": boolean;
  "spam.corroborated": boolean;
  "customer.high_frustration": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
