# generated by systemoneprompts — do not edit. source: ticket.toml sha256:129672eb76f1afd87e3922e512324c3b954f3608a49d7f8a219b769ecdd5f671
from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal, TypedDict, cast

from systemoneprompts import create_factor_evaluator, create_state_assert

meta: dict[str, Any] = {
    'title': 'Cloudflare Clef ticket decisions',
    'provider': 'cloudflare',
}
data: dict[str, Any] = {}
model: str | None = 'clef'
requires: dict[str, str] = {
    'ticket.message': 'string',
}
# Indexed requirements are enforced at runtime; generated list types follow the TypeScript element type.
# assert_state returns None and does not provide TypeScript-style narrowing.
class _ticket_RequiredState(TypedDict):
    message: str
class RequiredState(TypedDict):
    ticket: _ticket_RequiredState
assert_state = create_state_assert(requires)
questions: dict[str, dict[str, Any]] = {
    'duplicate': {
        'type': 'noul',
        'instructions': 'Does `ticket.message` report two charges for one order?',
        'criteria': {
            'true': 'Two charges for one order',
            'false': 'Only one charge',
        },
    },
    'department': {
        'type': 'choice',
        'instructions': 'Which department handles `ticket.message`?',
        'criteria': {
            'billing': 'Payments and refunds',
            'shipping': 'Delivery and tracking',
        },
    },
    'severity': {
        'type': 'score',
        'instructions': 'Rate the severity of `ticket.message`.',
        'criteria': [
            'No issue',
            {
                'issue': 'Payment or delivery requires correction',
            },
            'Permanent account loss',
        ],
    },
}
class _duplicate_Answer(TypedDict):
    type: Literal["noul"]
    noul: float
class _department_Answer(TypedDict):
    type: Literal["choice"]
    choice: Literal['billing', 'shipping']
    confidence: float
    probabilities: dict[str, float]
class _severity_Answer(TypedDict):
    type: Literal["score"]
    score: float
    confidence: float
    legend: dict[str, Any]
    probabilities: dict[str, float]
class Answers(TypedDict):
    duplicate: _duplicate_Answer
    department: _department_Answer
    severity: _severity_Answer
factor_definitions: dict[str, dict[str, Any]] = {
    'refund': {
        'ref': 'duplicate',
        'noul': {
            'gte': 0.8,
        },
    },
}
class Factors(TypedDict):
    refund: bool
evaluate_factors = cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))
