from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

from helpers import ROOT, fixture
from systemoneprompts import SystemOnePromptsError, generate, parse_definition, render_definition


def test_render_is_deterministic() -> None:
    definition = parse_definition(fixture("golden/triage.toml"), filename="triage.toml")
    assert render_definition(definition, source_name="triage.toml") == render_definition(
        definition, source_name="triage.toml"
    )


def test_render_embeds_source_hash_and_types() -> None:
    definition = parse_definition(fixture("golden/triage.toml"), filename="triage.toml")
    out = render_definition(definition, source_name="triage.toml")
    assert "generated by systemoneprompts — do not edit. source: triage.toml sha256:" in out
    assert "class RequiredState" in out or "RequiredState = TypedDict" in out
    assert "class Answers" in out or "Answers = TypedDict" in out
    assert "class Factors" in out or "Factors = TypedDict" in out
    assert "assert_state = create_state_assert(requires)" in out
    assert "cast(Callable[[Answers], Factors], create_factor_evaluator(factor_definitions))" in out
    assert "spam.requests_credentials" in out
    assert "message: str" in out
    assert "open_orders: list[Any]" in out
    assert "class RequiredState(TypedDict):" in out
    assert "class Answers(TypedDict):" in out or "Answers = TypedDict('Answers'" in out
    assert "returns None" in out
    assert "total=False" not in out


def test_generate_lists_every_error() -> None:
    bad = """
[questions.topic]
type = "choice"
instructions = "Which?"
criteria = { billing = "Charges", orders = "Shipments" }

[questions.frustration]
type = "score"
instructions = "How?"
criteria = ["Calm", "Angry"]

[factors]
x = { ref = "topic", choice = "nope" }
y = { all = ["frustration"] }
"""
    definition = parse_definition(bad, filename="bad.toml")
    with pytest.raises(SystemOnePromptsError) as caught:
        generate(definition, Path("unused.py"), source_name="bad.toml")
    codes = sorted(item.code for item in caught.value.diagnostics)
    assert "unknown-option" in codes
    assert "non-boolean-ref" in codes


def test_generated_module_imports_and_typechecks(tmp_path: Path) -> None:
    definition = parse_definition(fixture("golden/triage.toml"), filename="triage.toml")
    output = generate(definition, tmp_path / "triage_generated.py", source_name="triage.toml")
    spec = importlib.util.spec_from_file_location("triage_generated", output)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.assert_state(
        {
            "ticket": {"message": "hi", "sender": {"email": "a@b.c", "display_name": "A"}},
            "customer": {"open_orders": []},
            "policy": {"sensitive_credentials": []},
        }
    )
    result = subprocess.run(
        [sys.executable, "-m", "mypy", "--strict", str(output)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_omitted_model_and_quoted_ids(tmp_path: Path) -> None:
    definition = parse_definition(fixture("golden/noul-string.toml"), filename="noul-string.toml")
    rendered = render_definition(definition, source_name="noul-string.toml")
    assert "model: str | None = None" in rendered
    reserved = parse_definition(
        """
[questions."__proto__"]
type = "noul"

[factors]
"not-ident" = { ref = "__proto__", noul = { gte = 0.5 } }
""",
        filename="reserved.toml",
    )
    out = generate(reserved, tmp_path / "reserved_generated.py", source_name="reserved.toml")
    text = out.read_text(encoding="utf-8")
    assert "Answers = TypedDict" in text or "class Answers" in text
    assert "Factors = TypedDict" in text


def _import_and_typecheck(output: Path) -> object:
    spec = importlib.util.spec_from_file_location(output.stem, output)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    result = subprocess.run(
        [sys.executable, "-m", "mypy", "--strict", str(output)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return module


def test_keywords_and_colliding_ids_generate_valid_modules(tmp_path: Path) -> None:
    definition = parse_definition(
        """
[requires]
"a.import" = "string"
"items[0].class" = "number"
"items[0].def" = "number"
"x.y.z" = "boolean"
"x_y.z" = "boolean"

[questions.class]
type = "noul"

[questions."a.b"]
type = "noul"

[questions.a_b]
type = "choice"
criteria = { yes = "Yes", no = "No" }

[questions."a-b"]
type = "score"
criteria = ["Low", "High"]

[factors]
def = { all = ["class"] }
""",
        filename="keywords.toml",
    )
    output = generate(definition, tmp_path / "keywords_generated.py", source_name="keywords.toml")
    text = output.read_text(encoding="utf-8")
    aliases = [line for line in text.splitlines() if line.startswith("class _") and "Answer" in line]
    assert len(aliases) == 4 and len(set(aliases)) == 4, aliases
    module = _import_and_typecheck(output)
    module.assert_state(  # type: ignore[attr-defined]
        {
            "a": {"import": "x"},
            "items": [{"class": 1, "def": 2}],
            "x": {"y": {"z": True}},
            "x_y": {"z": False},
        }
    )
    factors = module.evaluate_factors(  # type: ignore[attr-defined]
        {
            "class": {"type": "noul", "noul": 0.9},
            "a.b": {"type": "noul", "noul": 0.1},
            "a_b": {"type": "choice", "choice": "yes", "confidence": 0.9, "probabilities": {}},
            "a-b": {"type": "score", "score": 1.0, "confidence": 0.9, "legend": {}, "probabilities": {}},
        }
    )
    assert factors == {"def": True}


def test_empty_tables_typecheck_under_strict_mypy(tmp_path: Path) -> None:
    definition = parse_definition('[questions.q]\ntype = "noul"\n', filename="minimal.toml")
    output = generate(definition, tmp_path / "minimal_generated.py", source_name="minimal.toml")
    text = output.read_text(encoding="utf-8")
    assert "meta: dict[str, Any] = {}" in text
    assert "requires: dict[str, str] = {}" in text
    assert "factor_definitions: dict[str, dict[str, Any]] = {}" in text
    module = _import_and_typecheck(output)
    assert module.evaluate_factors({"q": {"type": "noul", "noul": 0.2}}) == {}  # type: ignore[attr-defined]


def test_generated_module_exports_application_data(tmp_path: Path) -> None:
    definition = parse_definition(
        '''
[questions.topic]
type = "choice"
criteria = { cost = "Prices", timing = "Timing" }

[data]
labels = { cost = "Delivery prices", timing = "Delivery times" }
templates = [
  { id = "cost", text = "{method_label} costs {price_label}." },
]
''',
        filename="delivery.toml",
    )
    output = generate(definition, tmp_path / "delivery_generated.py", source_name="delivery.toml")
    module = _import_and_typecheck(output)
    assert module.data == {
        "labels": {"cost": "Delivery prices", "timing": "Delivery times"},
        "templates": [{"id": "cost", "text": "{method_label} costs {price_label}."}],
    }


def test_indexed_requirements_emit_element_types() -> None:
    definition = parse_definition(
        '[requires]\n"tickets[0].message" = "string"\n\n[questions.urgent]\ntype = "noul"\n',
        filename="indexed.toml",
    )
    rendered = render_definition(definition, source_name="indexed.toml")
    assert "tickets: list[" in rendered
    assert "message: str" in rendered
    assert "list[Any]" not in rendered
    wildcard = parse_definition(
        '[requires]\n"tickets[].message" = "string"\n\n[questions.urgent]\ntype = "noul"\n',
        filename="wildcard.toml",
    )
    wildcard_rendered = render_definition(wildcard, source_name="wildcard.toml")
    assert "tickets: list[" in wildcard_rendered
    assert "message: str" in wildcard_rendered
    assert "list[Any]" not in wildcard_rendered
