// generated by systemoneprompts — do not edit. source: taxonomy.toml sha256:a5e3f023ccdf94a8bbcc2401cf4e768cb84cd757c8b806d3990310ea0c839489
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Taxonomy walk helper",
  version: "0.1.0",
  description: "The walk is in run.ts; this file documents the leaf questions.",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "listing.title": "string",
  "listing.description": "string",
} as const;
export interface RequiredState {
  listing: {
    title: string;
    description: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  department: {
    type: "choice",
    instructions: {
      question: "Which top-level department fits `listing.title`?",
      focus: "Use the listing's intended use, not just the word bottle.",
    },
    criteria: {
      "Sporting Goods": "Athletic and outdoor equipment, including cycling accessories",
      "Home & Kitchen": "Household drinkware and kitchen goods",
    },
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {} as const;
export type Factors = Record<never, boolean>;
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
