// generated by systemoneprompts — do not edit. source: verify.toml sha256:7d48432ae49caf835a3b530c975d9e875d7e0c436d90e4d73476bd4331965f1b
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Tool-call verification",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "trace.tool": "string",
  "trace.arguments": "object",
  "trace.result": "object",
} as const;
export interface RequiredState {
  trace: {
    tool: string;
    arguments: {
      [k: string]: JsonValue;
    };
    result: {
      [k: string]: JsonValue;
    };
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  tool_exists: {
    type: "noul",
    instructions: "Does `trace.tool` name a real function that was invoked?",
  },
  args_match_schema: {
    type: "noul",
    instructions: {
      question: "Do `trace.arguments` match the tool's expected fields?",
      inspect: "`trace.arguments`",
    },
  },
  result_addresses_args: {
    type: "noul",
    instructions: {
      question: "Does `trace.result` answer the request implied by `trace.arguments`?",
      compare: [
        "`trace.arguments`",
        "`trace.result`",
      ],
    },
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  verified: {
    all: [
      "tool_exists",
      "args_match_schema",
      "result_addresses_args",
    ],
  },
} as const;
export interface Factors {
  verified: boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
