// generated by systemoneprompts — do not edit. source: batch.toml sha256:919916cdfceba72d2ced546ee29f35a903d0a6c7996f0fd96037824018312891
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Map-reduce ticket batch",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  topic: {
    type: "choice",
    instructions: "Which team should handle `ticket.message`?",
    criteria: {
      billing: "Charges, invoices, refunds",
      orders: "Shipments and deliveries",
      account: "Login and profile",
    },
  },
  urgent: {
    type: "noul",
    instructions: "Does `ticket.message` convey urgency?",
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "topic.billing": {
    ref: "topic",
    choice: "billing",
  },
  "urgent.yes": {
    ref: "urgent",
    noul: {
      gte: 0.5,
    },
  },
} as const;
export interface Factors {
  "topic.billing": boolean;
  "urgent.yes": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
