// generated by systemoneprompts — do not edit. source: score.toml sha256:bb7c2690e07c3350e5b6ffc8ebf534a64361765bda2f7e3dfebf13a94b2b6921
import type { EntryType, JsonValue, Questions, SystemOneResult } from "systemoneprompts";
import { createStateAssert, createFactorEvaluator, type StateAssert } from "systemoneprompts";

export const meta = {
  title: "Frustration score",
  version: "0.1.0",
} as const;
export const data = {} as const;
export const model = "jev-latest";

export const requires = {
  "ticket.message": "string",
} as const;
export interface RequiredState {
  ticket: {
    message: string;
    [k: string]: JsonValue;
  };
  [k: string]: JsonValue;
}
export const assertState: StateAssert<RequiredState> = createStateAssert(requires);

export const questions = {
  frustration: {
    type: "score",
    instructions: {
      question: "How frustrated does the customer appear?",
      inspect: "`ticket.message`",
    },
    criteria: [
      {
        what: "Calm and matter-of-fact",
        signals: [
          "Neutral wording",
        ],
      },
      {
        what: "Frustrated but civil",
        signals: [
          "Expresses annoyance",
        ],
      },
      {
        what: "Very angry or threatening to leave",
        signals: [
          "Hostile language",
        ],
      },
    ],
  },
} as const satisfies Questions;

export type Answers = SystemOneResult<typeof questions>["answers"];

export const factorDefinitions = {
  "customer.high_frustration": {
    ref: "frustration",
    score: {
      gte: 1.5,
    },
  },
} as const;
export interface Factors {
  "customer.high_frustration": boolean;
}
export const evaluateFactors = createFactorEvaluator<typeof questions, Factors>(factorDefinitions);
